//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UACEntities : DbContext
    {
        public UACEntities()
            : base("name=UACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRoll> UserRolls { get; set; }
        public virtual DbSet<UserRollsPermission> UserRollsPermissions { get; set; }
    
        public virtual int DeleteUserAndPermissions(Nullable<int> rollsId)
        {
            var rollsIdParameter = rollsId.HasValue ?
                new ObjectParameter("RollsId", rollsId) :
                new ObjectParameter("RollsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUserAndPermissions", rollsIdParameter);
        }
    }
}
