//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int CreatedBy { get; set; }
        public int RollsID { get; set; }
        public string Password { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual UserRoll UserRoll { get; set; }
    }
}
