//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRollsPermission
    {
        public int PermissionId { get; set; }
        public string Module { get; set; }
        public string Permission { get; set; }
        public int RollsId { get; set; }
        public bool IsEnable { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual UserRoll UserRoll { get; set; }
    }
}
